spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/university?createDatabaseIfNotExist=true
    username: root
    password: myNewPassword111!